# Generated by Django 5.2 on 2025-04-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('AIDS', 'AI & Data Science'), ('AIMl', 'AI & Machine Learning'), ('CSE', 'Computer Science'), ('VLSI', 'Electrical Engineering'), ('IIOT', 'Internet of Things'), ('CSE-CS', 'Computer Science - Cyber Security'), ('CSE-AM', 'Computer Science - Applied Maths')], max_length=100),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('description', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='students.student')),
            ],
        ),
    ]
