# Generated by Django 5.2 on 2025-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_department_internship_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('AIDS', 'AI & Data Science'), ('AIML', 'AI & Machine Learning'), ('CSE', 'Computer Science'), ('VLSI', 'Electrical Engineering'), ('IIOT', 'Internet of Things'), ('CSE-CS', 'Computer Science - Cyber Security'), ('CSE-AM', 'Computer Science - Applied Maths')], max_length=100),
        ),
    ]
