# Generated by Django 5.2 on 2025-04-15 16:30

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_internship_end_date_internship_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('opportunity_type', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement')], max_length=20)),
                ('deadline', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.AlterField(
            model_name='internship',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[students.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/', validators=[students.models.validate_file_size]),
        ),
    ]
